# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

version: 4.0.23
title: Javier Arce
author: Javier Arce
email: email@javier.computer
generator: Magic
destination: docs
timezone: Europe/Madrid # add your own locale timezone
description: Javier Arce
baseurl: "" 
url: "https://javier.computer"
twitter_username: javier
github_username:  javierarce

sass:
  load_paths:
    - _sass
    - _home
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-feed
  - jekyll-wikilinks

paginate: 10
paginate_path: "/page/:num/"

collections:
  photos:
    output: true
    permalink: '/photos/:path/'
  projects:
    output: true
    permalink: '/projects/:path/'
  texts:
    output: true
    permalink: '/texts/:path/'
  concepts:
    output: true
    permalink: '/concepts/:path/'
  books:
    output: true
    permalinks: '/books/:path'
collections_dir: content

permalink: /:year/:month/:day/:title

wikilinks:
  enable: true
  exclude: []
d3_graph_data:
  enabled: false
  exclude: []

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
