name: A workflow to create a jekyll post from github issue
on:
  issue_comment:
    types: [created]
jobs:
  build:
    name: A job to create a jekyll post from github issue
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'publish'
    steps:
      - name: Checkout main branch
        uses: actions/checkout@master

      - name: Create jekyll post file
        if: success() && github.event.issue.user.login == env.GITHUB_ACCOUNT_JEKYLL_OWNER
        run: |
          DATE="${{ github.event.issue.created_at }}"
          POST_TITLE=$(sed -E 's/[[:space:]|[:punct:]]/_/g' <<<'${{ github.event.issue.title }}')
          cat <<'EOF' > $POST_DIRECTORY/"${DATE:0:10}-${POST_TITLE}".md
          ---
          layout: post
          title: "${{ github.event.issue.title }}"
          date: ${{ build.created_at }}
          ---
          ${{ github.event.issue.body }}
          EOF
        env:
          GITHUB_ACCOUNT_JEKYLL_OWNER: 'javierarce'
          POST_DIRECTORY: 'content/_posts'
      - name: Commit files
        if: success()
        run: |
          git config --local user.name "$GIT_USER_NAME"
          git config --local user.email "$GIT_USER_EMAIL"
          git add --all
          # commit only if there are changes
          if [[ `git status --porcelain` ]]; then
            git commit -m "$DEFAULT_COMMIT_MESSAGE" -a
          fi
        env:
          GIT_USER_NAME: 'Javier Arce'
          GIT_USER_EMAIL: 'javierarce@gmail.com'
          DEFAULT_COMMIT_MESSAGE: 'New jekyll post create from github issue'

      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
           ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
